,
  "cash-home-buyer-jefferson-nj": ["avoid-foreclosure-jefferson-nj", "selling-nj-house-without-repairs"],
  "selling-nj-house-without-repairs": ["what-does-cash-home-buyer-nj-do", "how-to-get-fair-cash-offer-nj-home"],
  "what-does-cash-home-buyer-nj-do": ["selling-nj-house-without-repairs", "cheap-cash-home-buyers-new-jersey"],
};
ax-drain-caldwell"],
  "avoid-essex-county-tax-drain-caldwell": ["fair-cash-offer-cedar-grove-house", "nj-homeowners-hidden-tax-trap-2025"],
  "cash-house-buyer-belleville-nj-reasons": ["we-buy-houses-belleville-nj-2025", "tired-of-showings-sell-belleville-home-as-is"],
  "selling-bloomfield-property-as-is": ["what-bloomfield-sellers-should-know", "selling-house-as-is-bloomfield-nj-2025"],
  "west-milford-real-estate-market-2026": ["sell-house-as-is-west-milford-nj", "cash-home-buyers-passaic-county-nj-2025"]mfield-sellers-should-know": ["selling-bloomfield-property-as-is", "selling-house-as-is-bloomfield-nj-2025"],
  "fair-cash-offer-cedar-grove-house": ["verona-nj-cash-home-buyers", "avoid-essex-county-t-is": ["we-buy-houses-belleville-nj-2025", "cash-house-buyer-belleville-nj-reasons"],
  "what-bloo
  "tired-of-showings-sell-belleville-home-asnherited-property-new-jersey-sell-quickly", "sell-inherited-home-essex-county-nj"],se-without-repairs"],
  "probate-property-sales-new-jersey": ["iash-offer-nj-home": ["what-does-cash-home-buyer-nj-do", "selling-nj-houty-sales-new-jersey"],
  "how-to-get-fair-cckly": ["sell-inherited-home-essex-county-nj", "probate-properew-jersey-sell-quih-offer-nj-home"],
  "inherited-property-nhow-to-get-fair-caspairs-clutter-nj", "["sell-home-memories-rer-nj": er-nj"],
  "your-home-our-offe", "sell-home-memories-repairs-clutt["sell-home-before-holidays-njrn-property-into-purpose-holiday": r-home-our-offer-nj"],
  "tue-holiday", "youturn-property-into-purposdays-nj": ["ore-holidays-nj"],
  "sell-home-before-holis-clutter-nj": ["your-home-our-offer-nj", "sell-home-befto-get-fair-cash-offer-nj-home"],
  "sell-home-memories-repairwithout-repairs"],
  "verona-nj-cash-home-buyers": ["fair-cash-offer-cedar-grove-house", "how-ket-2026", "selling-nj-house-t-milford-nj": ["west-milford-real-estate-marid-foreclosure-clifton-nj-2025", "cash-home-buyer-jefferson-nj"],
  "sell-house-as-is-wese-as-is-jersey-city-nj": ["selling-nj-house-without-repairs", "what-does-cash-home-buyer-nj-do"],
  "we-buy-houses-paramus-nj": ["sell-house-fast-rutherford-nj-2025", "we-buy-houses-kearny-nj-2025"],
  "avoid-foreclosure-jefferson-nj": ["avop-cash-home-buyers-new-jersey-2025": ["cheap-cash-home-buyers-new-jersey", "what-does-cash-home-buyer-nj-do"],
  "sell-house-fast-nutley-cash-buyer": ["sell-house-fast-nutley-nj-2025", "we-buy-houses-belleville-nj-2025"],
  "sell-housses-kearny-nj-2025", "sell-house-fast-nutley-nj-2025"],
  "nj-homeowners-hidden-tax-trap-2025": ["how-to-get-fair-cash-offer-nj-home", "divorce-selling-house-new-jersey-2025"],
  "tofer-nj-home"],
  "montclair-cash-home-buyers-2025": ["sell-inherited-home-essex-county-nj", "inherited-property-new-jersey-sell-quickly"],
  "sell-house-fast-rutherford-nj-2025": ["we-buy-houhome-buyer-nj-do"],
  "cash-house-buyers-cumberland-county-nj": ["sell-house-fast-nutley-nj-2025", "how-to-get-fair-cash-of"],
  "cheap-cash-home-buyers-new-jersey": ["top-cash-home-buyers-new-jersey-2025", "what-does-cash-ty-nj-2025": ["we-buy-houses-kearny-nj-2025", "avoid-foreclosure-clifton-nj-2025"],
  "cash-home-buyers-passaic-counll-house-fast-rutherford-nj-2025nty-nj-2025"],
  "we-buy-houses-kearny-nj-2025": ["cash-home-buyers-passaic-county-nj-2025", "sehome", "selling-nj-house-without-repairs"],
  "divorce-selling-house-new-jersey-2025": ["avoid-foreclosure-clifton-nj-2025", "cash-home-buyers-passaic-coufield-sellers-should-know", "selling-bloomfield-property-as-is"],
  "avoid-foreclosure-clifton-nj-2025": ["avoid-foreclosure-jefferson-nj", "divorce-selling-house-new-jersey-2025"],
  "sell-inherited-home-essex-county-nj": ["inherited-property-new-jersey-sell-quickly", "probate-property-sales-new-jersey"],
  "sell-fire-damaged-house-new-jersey": ["how-to-get-fair-cash-offer-nj-e-buyer-belleville-nj-reasons"],
  "selling-house-as-is-bloomfield-nj-2025": ["what-bloom"],
  "we-buy-houses-belleville-nj-2025": ["tired-of-showings-sell-belleville-home-as-is", "cash-housleville-nj-2025", "sell-house-fast-nutley-cash-buyerstring, string[]> = {
  "sell-house-fast-nutley-nj-2025": ["we-buy-houses-bel
export const relatedSlugs: Record<ed articles mapping// All 38 blog post slugs with relat